# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: build
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build.yml'
  release:
    types: [ published ]
jobs:
  push_to_registry:
    name: Compile
    runs-on: ubuntu-latest
    env:
      STOML_VERSION: "v0.7.0"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Install STOML (BASH TOML parser)"
        run: |
          mkdir -p "target/tools"
          wget "https://github.com/freshautomations/stoml/releases/download/${{ env.STOML_VERSION }}/stoml_linux_amd64" \
              -O "target/tools/stoml"
          chmod +x "target/tools/stoml"

      - name: "Setup Python 3"
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'

      - name: "Install the RESUE tool"
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            reuse

      - name: "Get the Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: "Smart caching for rust/cargo"
        uses: Swatinem/rust-cache@v1

      - name: "Build"
        run: scripts/build

      - name: "Test & Check"
        run: scripts/test

